Repository status-im/status.im, pull requests merged in 2020-01, with the labels that each got.

#431 fix build process by removing bundle loop
  gulpfile.js
  package.json
  themes/navy/layout/layout.ejs
  themes/navy/source/js/main.js
Labels: bug

#441 Add a known issues section to the Status-React Quickstart Guide
  source/build_status/status_react_quickstart.md
Labels: docs

#452 add Teller and Assemble to the footer and update translations
  themes/navy/languages/ar.yml
  themes/navy/languages/en.yml
  themes/navy/languages/es.yml
  themes/navy/languages/fr.yml
  themes/navy/languages/ko.yml
  themes/navy/languages/ru.yml
  themes/navy/languages/zh.yml
  themes/navy/layout/partial/footer.ejs
Labels: enhancement
